### ISSUE TITLE
NullPointerException after installation

### ISSUE THREAD

**Issue by dima74** [swdotcom/swdc-intellij#20]
**Describe the bug**
I installed the plugin and registered on the website, then returned to IDE and start exploring the plugin features (click the icon in status bar, etc). At some point exception occurred (text below). The exception does not reproduce after IDE restart, so unfortunately I don't have steps for reproduction

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Install plugin
2. Plugin shows window with link to registration page
3. Go to website and register, return to IDE
4. Click to plugin icon in status bar

**ACTUAL RESULTS**
```
java.lang.NullPointerException
	at java.base/java.io.Writer.write(Writer.java:249)
	at com.softwareco.intellij.plugin.fs.FileManager.openReadmeFile(FileManager.java:259)
	at com.softwareco.intellij.plugin.tree.TreeItemBuilder$1.mouseClicked(TreeItemBuilder.java:83)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Plugin version: Code Time v1.0.4
 - IntelliJ info:
```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Runtime version: 11.0.6-internal+0-adhoc.dima.jbr11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.5.11-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 8125M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, PsiViewer, com.jetbrains.ChooseRuntime, com.mnw.tabmover, com.softwareco.intellij.plugin, com.wakatime.intellij.plugin, indent-rainbow.indent-rainbow, intellij.haskell, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, org.jetbrains.idea.grammar, org.toml.lang, org.rust.lang
```

Thanks for Code Time!

**Comment by xavluiz** [comment]
Thank you very much for reporting this. I've updated the marketplace with the newer build, 1.0.5.

**Comment by dima74** [comment]
Thank you!
