### ISSUE TITLE
Take up too much memory

### ISSUE THREAD

**Issue by AprilViolet** [swdotcom/swdc-intellij#25]
**Describe the bug**
Hello developer, I recently found that the memory occupied by the plugin is too large, it seems that the memory is leaking. For example, the same project is opened for the first time. Opening the plug-in will occupy at least 2 G of memory. This seems to have appeared in the last two versions, and it is still true until today's update to 1.0.22. I have compared a lot and it is definitely a plug-in problem.

**ISSUE TYPE**
- Bug Report

**Screenshots**
This is to open the plugin, and then open a simple ordinary project, do nothing and take up memory
![Snipaste_2020-04-10_19-53-06](https://user-images.githubusercontent.com/40155496/78989647-cb8b3500-7b66-11ea-9311-c06676422b74.png)

This is the same project above, close the plugin, and take up memory
![Snipaste_2020-04-10_19-58-04](https://user-images.githubusercontent.com/40155496/78989710-f1183e80-7b66-11ea-9095-e484e5e2adc4.png)

I have tried many projects, all of which are the same. Opening the plug-in takes at least 2G more memory than closing the plug-in

**Desktop (please complete the following information):**
 - OS: windows1909
 - Plugin version 1.0.22

**Comment by brettmstevens7** [comment]
@AprilViolet we made some updates to ensure we're deallocating threads appropriately - could you retest and let us know if memory is still high?

**Comment by AprilViolet** [comment]
@brettmstevens7 I just received an update for 1.0.29, but I'm sorry, the high memory usage still exists. Even after I uninstalled the plugin and reinstalled it, the memory usage was still too high.

**Comment by AprilViolet** [comment]
@brettmstevens7 It may be fixed. I uninstalled the plug-in, then cleared the cache of the plug-in under C: \ Users \ user \ .software, and then re-installed the plug-in. At present, the memory occupied is reasonable, and it is not as good as before high.

**Comment by brettmstevens7** [comment]
@AprilViolet thanks for the update and let me know if you see it go up again

**Comment by AprilViolet** [comment]
@brettmstevens7 I'm sorry that it seems that it still takes up too much memory. When I update to 2.0.0, it is still the same. Even IDEA warns that the memory is too large. I tested it several times, and once reported an error message like this, I do n’t know whether There are relationships

Access is allowed from event dispatch thread with IW lock only.
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@2ec2e476
Current thread: Thread[Timer-247,6,Idea Thread Group] 874753444
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1124420988
    at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1057)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1039)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.assertDispatchThread(FileEditorManagerImpl.java:1501)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1071)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.doOpenTextEditor(FileEditorManagerImpl.java:1157)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openTextEditor(FileEditorManagerImpl.java:1151)
    at com.softwareco.intellij.plugin.managers.FileManager.openReadmeFile(FileManager.java:313)
    at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfo(SoftwareCo.java:179)
    at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfoWhenProjectsReady(SoftwareCo.java:140)
    at com.softwareco.intellij.plugin.SoftwareCo.access$000(SoftwareCo.java:29)
    at com.softwareco.intellij.plugin.SoftwareCo$1.run(SoftwareCo.java:134)
    at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
    at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by AprilViolet** [comment]
But after reinstalling and clearing the C: \ Users \ user \ .software cache, the memory seems to be down again? I'm not sure, but I will still report the above error
