### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by hamedfaryabi** [swdotcom/swdc-intellij#27]
I installed plugin today and this error occured 88 times:
```paste below
java.lang.NullPointerException
	at com.softwareco.intellij.plugin.tree.TreeItemBuilder.buildTopFilesTree(TreeItemBuilder.java:419)
	at com.softwareco.intellij.plugin.tree.TreeItemBuilder.buildTopCodeTimeFilesTree(TreeItemBuilder.java:387)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow.rebuildTreeView(CodeTimeToolWindow.java:158)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow.access$100(CodeTimeToolWindow.java:20)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow$1.run(CodeTimeToolWindow.java:65)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
**ISSUE TYPE**
- Bug Report

**Desktop**
 - OS: Ubuntu 20.04
 - Plugin version [Code Time v2.2.5]
- PhpStorm Version 2020.1.1

**Comment by xavluiz** [comment]
Thank you for the error update and apologies for the inconvenience. The fix for this is going out with version 2.2.6 and should be available within 2 days based on the marketplace approval process.
