### ISSUE TITLE
Extension crash on IDE start, problem apparently related to json parsing

### ISSUE THREAD

**Issue by viccol961** [swdotcom/swdc-intellij#28]
**Describe the bug**

Every time I start InjelliJ, the warning for "IDE fatal errors" starts blinking and the associated window gives me the following stack trace :

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 12 path $[1]
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.softwareco.intellij.plugin.managers.FileManager.convertPayloadsToList(FileManager.java:595)
	at com.softwareco.intellij.plugin.managers.FileManager.getLastSavedKeystrokeStats(FileManager.java:585)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfo(SoftwareCo.java:191)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfoWhenProjectsReady(SoftwareCo.java:140)
	at com.softwareco.intellij.plugin.SoftwareCo.access$000(SoftwareCo.java:29)
	at com.softwareco.intellij.plugin.SoftwareCo$1.run(SoftwareCo.java:134)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 12 path $[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:713)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:697)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 11 more
```

After that, the extension properly records my code time but not any keystroke related data (see screenshot below, I had been coding for 3.7h as said, but I definitely typed more than 23 keystrokes).

**ISSUE TYPE**
- Bug Report

**Screenshots**

![[https://i.imgur.com/BMvsdVs.jpg](https://i.imgur.com/BMvsdVs.jpg)](https://i.imgur.com/BMvsdVs.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19041.329
 - Plugin version : CodeTime v2.2.9

**Additional context**

I'm also using the CodeTime extension for VS Code and I have not detected any bugs over there.

**Comment by xavluiz** [comment]
Hi,
Thank you for the issue report with the stack trace and screen shot. We really appreciate that info. I'll look into this now and report back as soon as I can. We apologize for any inconvenience.
Regards.

**Comment by xavluiz** [comment]
We have a fix to ensure the json string is cleaned before parsing and will publish a fix to the marketplace shortly. It may take a day or two for Jetbrains to approve the request. Thanks.

**Comment by viccol961** [comment]
Just received the update. Everything seems to work.

Many thanks !
