### ISSUE TITLE
Crashes on start on Android studio

### ISSUE THREAD

**Issue by tolotrasamuel** [swdotcom/swdc-intellij#31]
![image](https://user-images.githubusercontent.com/29230303/88283699-fc017400-ccfc-11ea-96a4-752b40c31132.png)

**Describe the bug**
```paste below
Install latest version 2.2.11
Restart Android studio
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version  2.2.11

**Additional context**
```paste below

```

**Comment by ichisadashioko** [comment]
Is there any updates on this? I think we should downgrade the JDK version used to build the plugin to solve this bug.

**Comment by xavluiz** [comment]
We apologize for the delay. We are looking into this now and provide details as soon as possible. Thank you.

**Comment by xavluiz** [comment]
Thank you for your patience. We will build it with Java 11 of class file version 55. I'll report back here once the marketplace has published the latest build.

**Comment by ohari5336** [comment]
hello everyone I also see this error on installing the plugin

Log:

`Plugin 'com.softwareco.intellij.plugin' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.UnsupportedClassVersionError: com/softwareco/intellij/plugin/SoftwareCo has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:636)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`


![image](https://user-images.githubusercontent.com/22674877/89701310-2a18c200-d953-11ea-8435-7d44aadb5e32.png)


![image](https://user-images.githubusercontent.com/22674877/89701307-238a4a80-d953-11ea-8496-2e283e0fe06c.png)

**Comment by xavluiz** [comment]
Thank you for your patience. We've completed the deployment to the JetBrains marketplace with the JDK version upgrade and handling that event dispatch thread issue.  v2.2.12 is now available and please let us know if you are experiencing any other issues. Regards.

**Comment by xavluiz** [comment]
We apologize, it looks like we will need to research the JDK version we're using to build the plugin and will update this thread soon. We should have a new version available that is backward compatible for various IDE versions soon. Thank you.

**Comment by ichisadashioko** [comment]
I think there is a `--target` option to support "any" older `JDK` versions.

**Comment by ohari5336** [comment]
I try your plugin new version first I search on android studio plugins marketplace but not showing any plugins (maybe my internet connection slow) then I download your new version of the plugin from here: [this](https://github.com/swdotcom/swdc-intellij/blob/main/softwareco.zip)

then install on android studio and restart but after a long time my studio not started automatically then I force stop current process than manually start and after started plugin is activated and working fine

thanks for fixing this

**Comment by brettmstevens7** [comment]
Thanks for testing @ohari5336. Closing this issue but please reopen if you have any issues @tolotrasamuel.
