### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by genesiscz** [swdotcom/swdc-intellij#36]
**Describe the bug**
```paste below
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $[4]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.softwareco.intellij.plugin.managers.FileManager.convertPayloadsToList(FileManager.java:567)
	at com.softwareco.intellij.plugin.managers.FileManager.getLastSavedKeystrokeStats(FileManager.java:552)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfo(SoftwareCo.java:180)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfoWhenProjectsReady(SoftwareCo.java:145)
	at com.softwareco.intellij.plugin.SoftwareCo.access$000(SoftwareCo.java:30)
	at com.softwareco.intellij.plugin.SoftwareCo$1.run(SoftwareCo.java:140)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $[4]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 13 more
```

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Just open the IDE. It hits the exception in the toolbar. It happends for a few weeks now, update didnt help.-

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin version 2.2.15

**Comment by xavluiz** [comment]
Thank you for the issue report and we apologize for the response delay. We'll look into this now.
Regards

**Comment by xavluiz** [comment]
A json metrics file seems to have been malformed. We have a fix for this that will go out in the next couple of days after days.
Regards.

**Comment by genesiscz** [comment]
looks resolved
