### ISSUE TITLE
Stacktrace Error upon updating IntelliJ to newest Update

### ISSUE THREAD

**Issue by RobFosterNYC** [swdotcom/swdc-intellij#37]
I installed an update that was available for IntelliJ IDEA community edition.
As soon as it was finished and the IDE rebooted.
I got this stacktrace error.
.
`
java.lang.UnsatisfiedLinkError: Unable to load library 'C:\Users\Studio\AppData\Roaming\JetBrains\IdeaIC2020.2\plugins\softwareco\lib\windows64\libsodium.dll':
The system cannot find the path specified.

The system cannot find the path specified.

Native library (win32-x86-64/C:\Users\Studio\AppData\Roaming\JetBrains\IdeaIC2020.2\plugins\softwareco\lib\windows64\libsodium.dll) not found in resource path (C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\bootstrap.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\extensions.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\util.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\jdom.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\log4j.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\trove4j.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\jna.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1722)
	at co.libly.resourceloader.SharedLibraryLoader.registerLibraryWithClasses(SharedLibraryLoader.java:81)
	at co.libly.resourceloader.SharedLibraryLoader.loadSystemLibrary(SharedLibraryLoader.java:43)
	at com.goterl.lazycode.lazysodium.utils.LibraryLoader.loadAbsolutePath(LibraryLoader.java:121)
	at com.goterl.lazycode.lazysodium.SodiumJava.<init>(SodiumJava.java:39)
	at com.swdc.snowplow.tracker.manager.HashManager.produceHash(HashManager.java:173)
	at com.swdc.snowplow.tracker.manager.HashManager.hashValue(HashManager.java:44)
	at com.swdc.snowplow.tracker.entities.ProjectEntity.buildContext(ProjectEntity.java:16)
	at com.swdc.snowplow.tracker.events.EditorActionEvent.buildContexts(EditorActionEvent.java:35)
	at com.swdc.snowplow.tracker.manager.TrackerManager.trackEditorAction(TrackerManager.java:85)
	at com.softwareco.intellij.plugin.managers.EventTrackerManager$3.run(EventTrackerManager.java:145)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
	Suppressed: java.lang.UnsatisfiedLinkError: The system cannot find the path specified.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 14 more
	Suppressed: java.lang.UnsatisfiedLinkError: The system cannot find the path specified.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 14 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/C:\Users\Studio\AppData\Roaming\JetBrains\IdeaIC2020.2\plugins\softwareco\lib\windows64\libsodium.dll) not found in resource path (C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\bootstrap.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\extensions.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\util.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\jdom.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\log4j.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\trove4j.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\jna.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 14 more
`

.
![Screenshot_32](https://user-images.githubusercontent.com/18384135/91531713-3604fd80-e8db-11ea-8675-81e269e61808.png)

**Comment by xavluiz** [comment]
Thank you for posting the detail issue report, this was very helpful. We'll remove the libsodium dependency and use a lightweight blake2b library that will not have these dependency issues. The new version will be available in a couple of days.
Regards.
