### ISSUE TITLE
Fatal Errors since last Update

### ISSUE THREAD

**Issue by jonathan-reichardt** [swdotcom/swdc-intellij#39]
I get 2 fatal errors when starting PhpStorm 2020.2 CT 2.2.16

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.softwareco.intellij.plugin.managers.FileManager.convertPayloadsToList(FileManager.java:567)
	at com.softwareco.intellij.plugin.managers.FileManager.getLastSavedKeystrokeStats(FileManager.java:552)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfo(SoftwareCo.java:180)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfoWhenProjectsReady(SoftwareCo.java:145)
	at com.softwareco.intellij.plugin.SoftwareCo.access$000(SoftwareCo.java:30)
	at com.softwareco.intellij.plugin.SoftwareCo$1.run(SoftwareCo.java:140)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 13 more

and

java.lang.UnsatisfiedLinkError: Unable to load library 'C:\Users\ReichardtJ\AppData\Roaming\JetBrains\PhpStorm2020.2\plugins\softwareco\lib\windows64\libsodium.dll':
Das System kann den angegebenen Pfad nicht finden.

Das System kann den angegebenen Pfad nicht finden.

Native library (win32-x86-64/C:\Users\ReichardtJ\AppData\Roaming\JetBrains\PhpStorm2020.2\plugins\softwareco\lib\windows64\libsodium.dll) not found in resource path (C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\bootstrap.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\extensions.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\util.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\jdom.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\log4j.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\trove4j.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\jna.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1722)
	at co.libly.resourceloader.SharedLibraryLoader.registerLibraryWithClasses(SharedLibraryLoader.java:81)
	at co.libly.resourceloader.SharedLibraryLoader.loadSystemLibrary(SharedLibraryLoader.java:43)
	at com.goterl.lazycode.lazysodium.utils.LibraryLoader.loadAbsolutePath(LibraryLoader.java:121)
	at com.goterl.lazycode.lazysodium.SodiumJava.<init>(SodiumJava.java:39)
	at com.swdc.snowplow.tracker.manager.HashManager.produceHash(HashManager.java:173)
	at com.swdc.snowplow.tracker.manager.HashManager.hashValue(HashManager.java:44)
	at com.swdc.snowplow.tracker.entities.ProjectEntity.buildContext(ProjectEntity.java:16)
	at com.swdc.snowplow.tracker.events.EditorActionEvent.buildContexts(EditorActionEvent.java:35)
	at com.swdc.snowplow.tracker.manager.TrackerManager.trackEditorAction(TrackerManager.java:85)
	at com.softwareco.intellij.plugin.managers.EventTrackerManager$3.run(EventTrackerManager.java:145)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
	Suppressed: java.lang.UnsatisfiedLinkError: Das System kann den angegebenen Pfad nicht finden.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 14 more
	Suppressed: java.lang.UnsatisfiedLinkError: Das System kann den angegebenen Pfad nicht finden.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 14 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/C:\Users\ReichardtJ\AppData\Roaming\JetBrains\PhpStorm2020.2\plugins\softwareco\lib\windows64\libsodium.dll) not found in resource path (C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\bootstrap.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\extensions.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\util.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\jdom.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\log4j.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\trove4j.jar;C:\Users\ReichardtJ\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\202.6948.87\lib\jna.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 14 more

**Comment by lots0logs** [comment]
This is also not the first time an update completely broke things. IJS 

```
Plugin 'com.softwareco.intellij.plugin' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader com.intellij.ide.plugins.cl.PluginClassLoader @63fa9c05 of the current class, org/slf4j/LoggerFactory, and the class loader com.intellij.util.lang.UrlClassLoader @578486a3 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @63fa9c05, parent loader 'bootstrap'; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @578486a3, parent loader 'platform')
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
    at com.snowplowanalytics.snowplow.tracker.http.OkHttpClientAdapter.<clinit>(OkHttpClientAdapter.java:42)
    at com.swdc.snowplow.tracker.manager.TrackerManager.<init>(TrackerManager.java:45)
    at com.softwareco.intellij.plugin.managers.EventTrackerManager.init(EventTrackerManager.java:44)
    at com.softwareco.intellij.plugin.managers.EventTrackerManager.<init>(EventTrackerManager.java:40)
    at com.softwareco.intellij.plugin.managers.EventTrackerManager.getInstance(EventTrackerManager.java:34)
    at com.softwareco.intellij.plugin.SoftwareCoEventManager.<init>(SoftwareCoEventManager.java:47)
    at com.softwareco.intellij.plugin.SoftwareCoEventManager.getInstance(SoftwareCoEventManager.java:39)
    at com.softwareco.intellij.plugin.SoftwareCo.<init>(SoftwareCo.java:37)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:664)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:260)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:346)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:346)
    at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:193)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
    at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:419)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by xavluiz** [comment]
Thank you for the issue update. We have a fix to ensure the json data is correctly handled in v2.2.20, which should be available within a couple of days.
Regards
