### ISSUE TITLE
2.20 another NullPointerException

### ISSUE THREAD

**Issue by genesiscz** [swdotcom/swdc-intellij#42]
**Describe the bug**

```paste below
java.lang.NullPointerException
	at com.softwareco.intellij.plugin.managers.FileManager.lambda$getLastSavedKeystrokeStats$1(FileManager.java:564)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at com.softwareco.intellij.plugin.managers.FileManager.getLastSavedKeystrokeStats(FileManager.java:564)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfo(SoftwareCo.java:180)
	at com.softwareco.intellij.plugin.SoftwareCo.initializeUserInfoWhenProjectsReady(SoftwareCo.java:145)
	at com.softwareco.intellij.plugin.SoftwareCo.access$000(SoftwareCo.java:30)
	at com.softwareco.intellij.plugin.SoftwareCo$1.run(SoftwareCo.java:140)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```
**ISSUE TYPE**
- Bug Report
- Window- Webstorm, Phpstorm

**Comment by xavluiz** [comment]
Thank you for the issue update. We'll look into this right away.
Regards

**Comment by xavluiz** [comment]
@genesiscz We've published v2.2.21 today with the fix for the NPE. This was a result of having only 1 element to sort through which we've replaced with a comparator.  This version should be available on the marketplace within 2 days based on JetBrains review process.
Regards.

**Comment by genesiscz** [comment]
Does the progress upload or is it all lost? Thanks!

**Comment by genesiscz** [comment]
![image](https://user-images.githubusercontent.com/1512353/92416779-6c563e80-f15f-11ea-9535-664b59c6d1ae.png)

What now?

**Comment by xavluiz** [comment]
I see. We have a test to validate sorting the list so we'll need to investigate what is causing the NPE. I will look into this right away. In regards to your earlier question, the progress will not be lost. This is an issue in showing information in the code time tree.

**Comment by xavluiz** [comment]
Hi, we've updated our plugin bundle to ensure this is not thrown. But before we publish to the marketplace would you like to download the 2.2.22 version from our github repo and install manually?

https://github.com/swdotcom/swdc-intellij/blob/main/softwareco.zip?raw=true

Thank you.
