### ISSUE TITLE
unable to get the line count for file

### ISSUE THREAD

**Issue by alexyershov** [swdotcom/swdc-intellij#7]
CodeTime 0.2.6, GoLand 2019.1, MacOS 10.14.5

java.lang.Throwable: Code Time: unable to get the line count for file /dummy.sql
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.softwareco.intellij.plugin.SoftwareCoEventManager.getLineCount(SoftwareCoEventManager.java:86)
	at com.softwareco.intellij.plugin.SoftwareCoEventManager.lambda$handleChangeEvents$0(SoftwareCoEventManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zclancy** [comment]
I've noticed the same error while using PyCharm's Python Console while running a program in the debugger.

Code Time v0.2.6, PyCharm 2019.1.1, MacOS 10.14.4

```
java.lang.Throwable: Code Time: unable to get the line count for file /Python Console
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.softwareco.intellij.plugin.SoftwareCoEventManager.getLineCount(SoftwareCoEventManager.java:86)
	at com.softwareco.intellij.plugin.SoftwareCoEventManager.lambda$handleChangeEvents$0(SoftwareCoEventManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by jralison** [comment]
I'm getting same error in PhpStorm 2019.1.1 and WebStorm 2019.1.1.
The CodeTime plugin version currently installed is 0.2.6.

PhpStorm is outputting following message:

```
java.lang.Throwable: Code Time: unable to get the line count for file /Dummy.txt
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.softwareco.intellij.plugin.SoftwareCoEventManager.getLineCount(SoftwareCoEventManager.java:86)
	at com.softwareco.intellij.plugin.SoftwareCoEventManager.lambda$handleChangeEvents$0(SoftwareCoEventManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by andrewhli** [comment]
Hi there. Thanks for bringing this error up. We're working on it and will let you know when it's done. Apologies for the bug.

**Comment by brettmstevens7** [comment]
Hi all. We removed the bit of code causing this error. We'll improve how we're getting line count in the future.
